---
#helm install supplychain -f values/noproxy-and-novault/network-service.yaml -n supplychain-ns corda-network-service
#helm upgrade supplychain -f values/noproxy-and-novault/network-service.yaml -n supplychain-ns corda-network-service
global:
  serviceAccountName: bevel-auth
  cluster:
    provider: azure
    cloudNativeServices: false
  vault:
    type: kubernetes
  proxy:
    provider: none
    externalUrlSuffix: svc.cluster.local
storage:
  size: 1Gi
  dbSize: 5Gi
  allowedTopologies:
    enabled: false

settings:
  removeKeysOnDelete: true # this will erase keys

tls:
  enabled: false
