##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth.fullname" . }}-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "auth.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/part-of: {{ include "auth.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}   
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
data:
  authservice.conf: |+
{{ tpl (.Files.Get "files/authservice.conf") . | indent 4 }}

  run.sh: |+
{{ tpl (.Files.Get "files/run.sh") . | indent 4 }}
