#helm install init -f values/noproxy-and-novault/init.yaml -n supplychain-ns corda-init
global:
  serviceAccountName: bevel-auth
  vault:
    type: hashicorp
    role: vault-role
    address: http://vault.url:8200
    authPath: supplychain
    secretEngine: secretsv2
    secretPrefix: "data/supplychain"
    network: corda-enterprise
  cluster:
    provider: aws
    cloudNativeServices: false
    kubernetesUrl: "https://yourkubernetes.com"
