##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keys
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  did: |
{{ .Files.Get (printf "files/%s-did.json" .Values.newIdentity.name) | replace "\"" "" | indent 4 }}
  verkey: |
{{ .Files.Get (printf "files/%s-verkey.json" .Values.newIdentity.name) | replace "\"" "" | indent 4 }}

