##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Default values for cenm-auth chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  serviceAccountName: vault-auth
  cluster:
    provider: aws  # choose from: minikube | aws | azure | gcp
    cloudNativeServices: false # set to true to use Cloud Native Services (SecretsManager and IAM for AWS; KeyVault & Managed Identities for Azure)
  vault:
    type: hashicorp
    role: vault-role
    address: 
    authPath: supplychain
    secretEngine: secretsv2
    secretPrefix: "data/supplychain"
  proxy:
    #This will be the proxy/ingress provider. Can have values "ambassador" or "none"
    #Eg. provider: "ambassador"
    provider: "ambassador"
    #This field contains the external URL of the node
    #Eg. externalUrlSuffix: test.blockchaincloudpoc.com
    externalUrlSuffix: test.blockchaincloudpoc.com
  cenm:
    sharedCreds:
      truststore: password
      keystore: password
    auth:
      port: 8081

storage:
  size: 1Gi
  dbSize: 5Gi
  allowedTopologies:
    enabled: false

image: 
  #Provide the docker secret name in the namespace
  #Eg. pullSecret: regcred
  pullSecret:
  #Pull policy to be used for the Docker image
  #Eg. pullPolicy: IfNotPresent
  pullPolicy: IfNotPresent
  #Provide a valid image and version for auth service
  auth:
    repository: corda/enterprise-auth
    tag: 1.5.9-zulu-openjdk8u382
  #Provide a valid image and version for enterprise-cli service
  enterpriseCli:
    repository: corda/enterprise-cli
    tag: 1.5.9-zulu-openjdk8u382

# subjects
subjects:
  auth: "CN=Test TLS Auth Service Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"

# db related configuration
database:
  driverClassName: "org.h2.Driver"
  jdbcDriver: ""
  url: "jdbc:h2:file:./h2/auth-persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=0;AUTO_SERVER_PORT=0"
  user: "auth-db-user"
  password: "auth-db-password"
  runMigration: true

# auth specific settings 
creds:
  authInitUserName: admin
  authInitUserPassword: p4ssWord

# Sleep time (in seconds) after an error occured
sleepTimeAfterError: 300
# base dir path
baseDir: /opt/cenm
