##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zone.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: zone-service
    app.kubernetes.io/component: zone
    app.kubernetes.io/part-of: {{ include "zone.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: zone-statefulset
    app.kubernetes.io/component: zone
    app.kubernetes.io/part-of: {{ include "zone.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
  ports:
  - name: zone-enm
    protocol: TCP
    port: {{ .Values.global.cenm.zone.enmPort }}
    targetPort: {{ .Values.global.cenm.zone.enmPort }}
  - name: zone-admin
    protocol: TCP
    port: {{ .Values.global.cenm.zone.adminPort }}
    targetPort: {{ .Values.global.cenm.zone.adminPort }}
