##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gateway.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/part-of: {{ include "gateway.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}   
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
data:
  run.sh: |+
{{ tpl (.Files.Get "files/run.sh") . | indent 4 }}

  gateway.conf: |+
{{ tpl (.Files.Get "files/gateway.conf") . | indent 4 }}

  setupAuth.sh: |+
{{ .Files.Get "files/setupAuth.sh" | indent 4 }}

{{- tpl ((.Files.Glob "files/users/*.json").AsConfig) . | nindent 2 }}
{{- tpl ((.Files.Glob "files/roles/*.json").AsConfig) . | nindent 2 }}
{{- tpl ((.Files.Glob "files/groups/*.json").AsConfig) . | nindent 2 }}
