##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "gateway.fullname" . }}-job
  namespace: {{ .Release.Namespace }}  
  labels:
    app: {{ include "gateway.fullname" . }}-job
    app.kubernetes.io/name: gateway-job
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: {{ include "gateway.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
  annotations:
    helm.sh/hook-weight: "5"
spec:
  backoffLimit: {{ .Values.backoffLimit }}
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      imagePullSecrets:
      {{- if .Values.image.pullSecret }}
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      initContainers:
        - name: init-check-gateway
          image: {{ .Values.image.gateway.repository }}:{{ .Values.image.gateway.tag }}
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
          - |-
            echo Probing gateway.{{ .Release.Namespace }} port {{ .Values.global.cenm.gateway.port }}
            until nc -w 5 -vz gateway.{{ .Release.Namespace }} {{ .Values.global.cenm.gateway.port }} > /dev/null 2>&1
            do
              echo "Connect to gateway.{{ .Release.Namespace }} port {{ .Values.global.cenm.gateway.port }} (tcp) failed: Connection refused"
            done
            echo "Connection gateway.{{ .Release.Namespace }} port {{ .Values.global.cenm.gateway.port }} successful"
        - name: init-check-auth
          image: {{ .Values.image.gateway.repository }}:{{ .Values.image.gateway.tag }}
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
          - |-
            echo Probing  auth.{{ .Release.Namespace }} port {{ .Values.global.cenm.auth.port }}
            until nc -w 5 -vz auth.{{ .Release.Namespace }} {{ .Values.global.cenm.auth.port }} > /dev/null 2>&1
            do
              echo "Connect to auth.{{ .Release.Namespace }} port {{ .Values.global.cenm.auth.port }} (tcp) failed: Connection refused"
            done
            echo "Connection auth.{{ .Release.Namespace }} port {{ .Values.global.cenm.auth.port }} successful"
      containers:
        - name: main
          image: {{ .Values.image.gateway.repository }}:{{ .Values.image.gateway.tag }}
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
          - |-
            # run the auth users setup
            cd /opt/cenm/CM-FILES
            ./setupAuth.sh gateway.{{ .Release.Namespace }} {{ .Values.global.cenm.gateway.port }}
          volumeMounts:
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/setupAuth.sh
            subPath: setupAuth.sh
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/g/configuration-maintainers.json
            subPath: configuration-maintainers.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/g/network-maintainers.json
            subPath: network-maintainers.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/g/network-operation-readers.json
            subPath: network-operation-readers.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/g/network-operators.json
            subPath: network-operators.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/r/ConfigurationMaintainer.json
            subPath: ConfigurationMaintainer.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/r/NetworkMaintainer.json
            subPath: NetworkMaintainer.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/r/NetworkOperationsReader.json
            subPath: NetworkOperationsReader.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/r/NetworkOperator.json
            subPath: NetworkOperator.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/u/business-reader.json
            subPath: business-reader.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/u/config-maintainer.json
            subPath: config-maintainer.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/u/network-maintainer.json
            subPath: network-maintainer.json
          - name: gateway-conf
            mountPath: /opt/cenm/CM-FILES/u/network-operator.json
            subPath: network-operator.json
      restartPolicy: OnFailure
      volumes:
        - name: gateway-conf
          configMap:
            name: {{ include "gateway.fullname" . }}-conf
            defaultMode: 0777
