##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gateway-service
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: {{ include "gateway.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gateway-statefulset
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: {{ include "gateway.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
  ports:
  - name: gateway
    protocol: TCP 
    port: {{ .Values.global.cenm.gateway.port }}
    targetPort: {{ .Values.global.cenm.gateway.port }}
