#helm install genesis -f values/noproxy-and-novault/genesis.yaml -n supplychain-bes besu-genesis
global:
  serviceAccountName: bevel-auth
  vault:
    type: kubernetes
  cluster:
    provider: azure # choose from: minikube | aws | azure | gcp
    cloudNativeServices: false
    
settings:
  # Flag to ensure the genesis configmaps are removed on helm uninstall
  removeGenesisOnDelete: true
  # Flag to copy domain and pool genesis from files for secondary members
  secondaryGenesis: true
