---
#helm install member-2 -f values/noproxy-and-novault/txnode-sec.yml -n carrier-bes besu-node
global:
  serviceAccountName: bevel-auth
  cluster:
    provider: azure # choose from: minikube | aws | azure | gcp
    cloudNativeServices: false
  vault:
    type: kubernetes
    network: indy
  proxy:
    provider: none

settings:
  removeKeysOnDelete: true
  identities:
    trustee: 
    endorser: university-endorser
    stewards: 
    - university-steward-1
    - university-steward-2
    - university-steward-3
